export const CRUD_MODE_UPDATE = "CRUD_MODE_UPDATE";
export const CRUD_MODE_CREATE = "CRUD_MODE_CREATE";

export const ACCESS_TOKEN = "ACCESS_TOKEN";
export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const IS_LOGGGED_IN = "IS_LOGGGED_IN";
